services:
  api:
    build:
      context: ./backend
      dockerfile: ../ops/backend.Dockerfile
    env_file:
      - ./ops/.env.local
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    command: ["node", "dist/main.js"]

  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: healthconnect_desktop
      POSTGRES_USER: hc
      POSTGRES_PASSWORD: hcpassword
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

volumes:
  pgdata:
